geonode/documents/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .views import DocumentUploadView, DocumentUpdateView

js_info_dict = {
    'packages': ('geonode.documents',),
}

urlpatterns = patterns('geonode.documents.views',
                       url(r'^$',
                           TemplateView.as_view(template_name='documents/document_list.html'),
                           name='document_browse'),
                       url(r'^(?P<docid>\d+)/?$',
                           'document_detail',
                           name='document_detail'),
                       url(r'^(?P<docid>\d+)/download/?$',
                           'document_download',
                           name='document_download'),
                       url(r'^(?P<docid>\d+)/replace$',
                           login_required(DocumentUpdateView.as_view()),
                           name="document_replace"),
                       url(r'^(?P<docid>\d+)/remove$',
                           'document_remove',
                           name="document_remove"),
                       url(r'^upload/?$',
                           login_required(DocumentUploadView.as_view()),
                           name='document_upload'),
                       url(r'^search/?$',
                           'document_search_page',
                           name='document_search_page'),
                       url(r'^(?P<docid>\d+)/metadata$',
                           'document_metadata',
                           name='document_metadata'),
                       )

geonode/project/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .views import ProjectUpdateView, GeocyberUploadView

js_info_dict = {
    'packages': ('geonode.project',),
}

urlpatterns = patterns('geonode.project.views',
                       url(r'^$',
                           TemplateView.as_view(template_name='documents/project_list.html'),
                           name='project_browse'),

                       url(r'^(?P<docid>\d+)/?$',
                           'project_detail',
                           name='project_detail'),
                       url(r'^(?P<docid>\d+)/download/?$',
                           'project_download',
                           name='project_download'),
                       url(r'^(?P<docid>\d+)/replace$',
                           login_required(ProjectUpdateView.as_view()),
                           name="project_replace"),
                       url(r'^(?P<docid>\d+)/remove$',
                           'project_remove',
                           name="project_remove"),

                       url(r'^search/?$',
                           'document_search_page',
                           name='document_search_page'),

                       url(r'^(?P<docid>\d+)/metadata$',
                           'project_metadata',
                           name='project_metadata'),
                       url(r'^upload/geocyber/?$',
                           login_required(GeocyberUploadView.as_view()),
                           name='geocyber_upload'),
                       )

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

from geonode.api.urls import api

import autocomplete_light

# Setup Django Admin
autocomplete_light.autodiscover()
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$',
                           TemplateView.as_view(template_name='index.html'),
                           name='home'),
                       url(r'^help/$',
                           TemplateView.as_view(template_name='help.html'),
                           name='help'),
                       url(r'^developer/$',
                           TemplateView.as_view(
                               template_name='developer.html'),
                           name='developer'),
                       url(r'^about/$',
                           TemplateView.as_view(template_name='about.html'),
                           name='about'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # Search views
                       url(r'^search/$',
                           TemplateView.as_view(
                               template_name='search/search.html'),
                           name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       # (r'^notifications/', include('notification.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),
                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                           name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                           name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$',
                           TemplateView.as_view(template_name='lang.js',
                                                content_type='text/javascript'),
                           name='lang'),
                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                           js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                           {'sitemaps': sitemaps}, name='sitemap'),
                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),
                       (r'^project/', include('geonode.project.urls')),
                       url(r'', include(api.urls)),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/',
                             include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^(?P<site>[A-Za-z0-9_\-]+)/$',
                         'geonode.maps.views.featured_map'),
                        (r'^(?P<site>[A-Za-z0-9_\-]+)/info$',
                            'geonode.maps.views.featured_map_info'),
                        )

geonode/documents/models.py
import logging
import os
import uuid

from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.contrib.contenttypes import generic
from django.contrib.staticfiles import finders
from django.utils.translation import ugettext_lazy as _

from geonode.layers.models import Layer
from geonode.base.models import ResourceBase, Thumbnail, Link, resourcebase_post_save
from geonode.maps.signals import map_changed_signal
from geonode.maps.models import Map

IMGTYPES = ['jpg', 'jpeg', 'tif', 'tiff', 'png', 'gif']

logger = logging.getLogger(__name__)


class Document(ResourceBase):

    """
    A document is any kind of information that can be attached to a map such as pdf, images, videos, xls...
    """

    # Relation to the resource model
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    resource = generic.GenericForeignKey('content_type', 'object_id')

    doc_file = models.FileField(upload_to='documents',
                                null=True,
                                blank=True,
                                verbose_name=_('File'))

    extension = models.CharField(max_length=128, blank=True, null=True)

    doc_type = models.CharField(max_length=128, blank=True, null=True)

    doc_url = models.URLField(
        blank=True,
        null=True,
        help_text=_('The URL of the document if it is external.'),
        verbose_name=_('URL'))

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('document_detail', args=(self.id,))

    @property
    def name_long(self):
        if not self.title:
            return str(self.id)
        else:
            return '%s (%s)' % (self.title, self.id)

    def _render_thumbnail(self):
        from cStringIO import StringIO

        size = 200, 150

        try:
            from PIL import Image, ImageOps
        except ImportError, e:
            logger.error(
                '%s: Pillow not installed, cannot generate thumbnails.' %
                e)
            return None

        try:
            # if wand is installed, than use it for pdf thumbnailing
            from wand import image
        except:
            wand_available = False
        else:
            wand_available = True

        if wand_available and self.extension and self.extension.lower(
        ) == 'pdf' and self.doc_file:
            logger.debug(
                'Generating a thumbnail for document: {0}'.format(
                    self.title))
            with image.Image(filename=self.doc_file.path) as img:
                img.sample(*size)
                return img.make_blob('png')
        elif self.extension and self.extension.lower() in IMGTYPES and self.doc_file:

            img = Image.open(self.doc_file.path)
            img = ImageOps.fit(img, size, Image.ANTIALIAS)
        else:
            filename = finders.find('documents/{0}-placeholder.png'.format(self.extension), False) or \
                finders.find('documents/generic-placeholder.png', False)

            if not filename:
                return None

            img = Image.open(filename)

        imgfile = StringIO()
        img.save(imgfile, format='PNG')
        return imgfile.getvalue()

    @property
    def class_name(self):
        return self.__class__.__name__

    class Meta(ResourceBase.Meta):
        pass

def get_related_documents(resource):
    if isinstance(resource, Layer) or isinstance(resource, Map):
        ct = ContentType.objects.get_for_model(resource)
        return Document.objects.filter(content_type=ct, object_id=resource.pk)
    else:
        return None


def pre_save_document(instance, sender, **kwargs):
    base_name, extension, doc_type = None, None, None

    if instance.doc_file:
        base_name, extension = os.path.splitext(instance.doc_file.name)
        instance.extension = extension[1:]
        doc_type_map = settings.DOCUMENT_TYPE_MAP
        if doc_type_map is None:
            doc_type = 'other'
        else:
            if instance.extension in doc_type_map:
                doc_type = doc_type_map[''+instance.extension]
            else:
                doc_type = 'other'
        instance.doc_type = doc_type

    elif instance.doc_url:
        if len(instance.doc_url) > 4 and instance.doc_url[-4] == '.':
            instance.extension = instance.doc_url[-3:]

    if not instance.uuid:
        instance.uuid = str(uuid.uuid1())
    instance.csw_type = 'document'

    if instance.abstract == '' or instance.abstract is None:
        instance.abstract = 'No abstract provided'

    if instance.title == '' or instance.title is None:
        instance.title = instance.name

    if instance.resource:
        instance.csw_wkt_geometry = instance.resource.geographic_bounding_box.split(
            ';')[-1]
        instance.bbox_x0 = instance.resource.bbox_x0
        instance.bbox_x1 = instance.resource.bbox_x1
        instance.bbox_y0 = instance.resource.bbox_y0
        instance.bbox_y1 = instance.resource.bbox_y1
    else:
        instance.bbox_x0 = -180
        instance.bbox_x1 = 180
        instance.bbox_y0 = -90
        instance.bbox_y1 = 90


def create_thumbnail(sender, instance, created, **kwargs):
    if not created:
        return

    if instance.has_thumbnail():
        instance.thumbnail_set.get().thumb_file.delete()
    else:
        instance.thumbnail_set.add(Thumbnail())

    image = instance._render_thumbnail()

    instance.thumbnail_set.get().thumb_file.save(
        'doc-%s-thumb.png' %
        instance.id,
        ContentFile(image))
    instance.thumbnail_set.get().thumb_spec = 'Rendered'
    instance.thumbnail_set.get().save()
    Link.objects.get_or_create(
        resource=instance.get_self_resource(),
        url=instance.thumbnail_set.get().thumb_file.url,
        defaults=dict(
            name=('Thumbnail'),
            extension='png',
            mime='image/png',
            link_type='image',))


def update_documents_extent(sender, **kwargs):
    model = 'map' if isinstance(sender, Map) else 'layer'
    ctype = ContentType.objects.get(model=model)
    for document in Document.objects.filter(content_type=ctype, object_id=sender.id):
        document.save()


signals.pre_save.connect(pre_save_document, sender=Document)
signals.post_save.connect(create_thumbnail, sender=Document)
signals.post_save.connect(resourcebase_post_save, sender=Document)
map_changed_signal.connect(update_documents_extent)

geonode/project/templates/documents/_document_filters.html
{% load i18n %}
{% load url from future %}

<ul class="nav nav-pills filter">
  <li><a href="{% url "document_browse" %}"{% if document_filter  == "date" %} class="selected"{% endif %}>{% trans "Most recent" %}</a></li>
  <li><a href="{% url "document_browse_popular" %}"{% if document_filter == "popular_count" %} class="selected"{% endif %}>{% trans "Most popular" %}</a></li>
  <li><a href="{% url "document_browse_shared" %}"{% if document_filter == "share_count" %} class="selected"{% endif %}>{% trans "Most shared" %}</a></li>
  {% comment %}
  <li>
    <form action="." class="form-inline">
      <label for="">{% trans "sort by:" %}</label>
      <select name="sort" id="layer_sort" class="span1">
        <option value="">{% trans "Newest" %}</option>
        <option value="">{% trans "Popularity" %}</option>
      </select>
    </form>
  </li>
{% endcomment %}
</ul>

geonode/project/templates/documents/_document_list_item.html
{% load url from future %}
{% load i18n %}
{% load agon_ratings_tags %}
{% load documents_tags %}
{% load base_tags %}
{% load geonode_auth %}

{% overall_rating document "document" as document_rating %}
{% num_ratings document as num_votes %}

{% has_obj_perm user document "base.view_resourcebase" as can_view_document %}

{% if can_view_document %}
<article>
  <div class="content">
    <!-- <div class="abstract-placeholder">{{ document.abstract }}</div> -->
    <div class="item-header">
        <a href="{% url "project_detail" document.id %}"><img class="thumb" src="{{ document.get_thumbnail_url }}" /></a>
      <h3><i class="icon-file-text-alt"></i> <a href="{% url "project_detail" document.id %}">{{ document.title }}</a></h3>
    </div>
    <div class="details">
      <div class="meta">
        <p>Doc {% trans 'from' %} <a href="{% url "profile_detail" document.owner.username %}">{{ document.owner }}</a>, {{ document.date|timesince }} {% trans 'ago' %}</p>
        <p class="abstract">{{ document.abstract }}</p>
        <ul class="nav stats">
          <li><a href="{% url "project_detail" document.id %}"><strong>{{ document.popular_count }}</strong> {% trans "view" %}{{ document.popular_count|pluralize }}</a></li>
          <li><a href="{% url "project_detail" document.id %}#rate"><strong><span class="overall_rating"></span></strong><span class="avg_rating" data-rating="{{ document_rating }}">{% trans "Average rating" %} ({{num_votes}} {% trans "votes" %})</span></a></li>
        </ul>
      </div>
      <div class="tools">
        <p><a href="{% if document.doc_file %}{% url "document_download" document.id %}{% endif %}" class="btn btn-mini">{% trans "Download" %}</a></p>
      </div>
    </div>
  </div>
</article>
{% else %}
<article>
    <div class="content">
        <div class="item-header">
            <img class="thumb" src="{{  STATIC_URL }}/geonode/img/missing_thumb.png" />
            <h3><i class="icon-file-text-alt"></i>{{ document.title }}</h3>
        </div>
        <div class="details">
            <div class="meta">
                <p>Doc {% trans 'from' %} <a href="{% url "profile_detail" document.owner.username %}">{{ document.owner }}</a>, {{ document.date|timesince }} {% trans 'ago' %}</p>
                <p class="abstract">{%  trans "You do not have permission to view this document" %}</p>
                <ul class="nav stats">
                    <li><a><strong>{{ document.popular_count }}</strong> {% trans "view" %}{{ document.popular_count|pluralize }}</a></li>
                    <li><a><strong><span class="overall_rating"></span></strong><span class="avg_rating" data-rating="{{ document_rating }}">{% trans "Average rating" %} ({{num_votes}} {% trans "votes" %})</span></a></li>
                </ul>
            </div>
            <div class="tools">
            </div>
        </div>
    </div>
</article>
{%  endif %}

geonode/project/templates/documents/document_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}
{% block body %}{% endblock body %}
{% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/project/templates/documents/document_remove.html
{% extends "documents/document_base.html" %}
{% load i18n %}

{% block title %}{{ document.title }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-8">
    <form action="{% url "document_remove" document.id %}" method="POST">
      <h2>
        {% blocktrans with document.title as document_title %}
          Are you sure you want to remove {{ document_title }}?
        {% endblocktrans %}
      </h2>
      {% csrf_token %}
      <input type="hidden" value="{{ document.typename }}" /> 
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ document.get_absolute_url }}" class="btn btn-info">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

geonode/project/templates/documents/document_replace.html
{% extends "documents/document_upload_base.html" %}
{% load i18n %}

{% block title %} {% trans "Replace Document" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents replace{% endblock body_class %}

{% block head %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}
  <div class="block">
    <div class="col-md-8">
      <h2 class="page-title">{% trans "Replace " %}{{ document.title }}</h2>
      <div id="upload_form">
        <form method="post" enctype="multipart/form-data" action="{% url "document_replace" document.id %}">
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          {{ form.errors }}
          {% if document.doc_file %}
            {{ form.doc_file }}
          {% elif document.doc_url %}
            {{ form.doc_url }}
          {% endif %}
          <section>
            <button id="clear-button" type="reset" class="btn btn-default">{% trans "Clear" %}</button>
            <button id="upload-button" type="submit" class="btn btn-danger" value="Update">{% trans "Replace Document" %}</button>
          </section>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

geonode/project/templates/documents/geocyber_upload.html
{% extends "documents/project_upload_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} Cargar Projecto {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}

<div class="col-md-8">
  <form id="upload_form"  method="post" enctype="multipart/form-data" action="{% url "geocyber_upload" %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    {{ form|as_bootstrap }}
    <button type="submit" id="upload-button" class="btn btn-danger">Subir</button>
  </form>

</div>

{% endblock %}

{% block sidebar %}

<div class="col-md-4">
  <h3>{% trans "Permissions"  %}</h3>
  <form id="permission_form">
    {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
{% include "_permissions_form_js.html" %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val());
        }
    });
    $("#resource").select2({
        minimumInputLength: 1,
        placeholder: 'Select layer, map or empty',
        width: 'element',
        ajax: {
          url: '{% url 'api_dispatch_list' api_name='api' resource_name='base' %}',
          data: function(term,page){
            return {
              type: 'layer,map',
              q: term.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
            }
          },
          results: function(data) {
            return {
              results: $.map(data.results,function(object){
                return {id: object.id, text: object.title, type: object._type};
              })
            }
          }          
        }
      });
    $('#resource').on('change',function(e){$('#resource_type').val($('#resource').select2('data').type)});
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
    });
</script>
{% endblock extra_script %}

geonode/project/templates/documents/project_list.html
{% extends "documents/project_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} Explora Proyectos - {{ block.super }} {% endblock %}

{% block body_class %}project project-list explore{% endblock %}

{% block body %}
  <div class="col-md-12">
    <!--<a href="{% url "document_upload" %}" class="btn btn-primary pull-right">{% trans "Upload Documents" %}</a> -->
    <a href="{% url "geocyber_upload" %}" class="btn btn-primary pull-right"> Cargar Proyecto </a>

    <h2 class="page-title">Explora Proyectos</h2>
  </div>
  {% with include_type_filter='true' %}
  {% with facet_type='project' %}
  {% with header='Project Type' %}
  {% with filter='doc_type__in' %}
  {% include "search/_search_content.html" %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% include "_bulk_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
  {% if GEONODE_SECURITY_ENABLED %}
    {% include "_permissions_form_js.html" %}
  {% endif %}
  <script type="text/javascript">
      {% if HAYSTACK_SEARCH %}
          SEARCH_URL = '{% url 'api_get_search' api_name='api' resource_name='projects'%}'
      {% else %}
          SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='projects' %}';
      {% endif %}
    FILTER_TYPE = 'project';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

geonode/project/templates/documents/project_remove.html
{% extends "documents/project_base.html" %}
{% load i18n %}

{% block title %}{{ document.title }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-8">
    <form action="{% url "project_remove" document.id %}" method="POST">
      <h2>
        {% blocktrans with document.title as document_title %}
          Are you sure you want to remove {{ document_title }}?
        {% endblocktrans %}
      </h2>
      {% csrf_token %}
      <input type="hidden" value="{{ document.typename }}" /> 
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ document.get_absolute_url }}" class="btn btn-info">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

geonode/project/templates/documents/project_upload.html
{% extends "documents/project_upload_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} Cargar Projecto {% endblock %}

{% block body_class %}project upload{% endblock body_class %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block body %}

<div class="col-md-8">
  <form id="upload_form"  method="post" enctype="multipart/form-data" action="{% url "geocyber_upload" %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    {{ form|as_bootstrap }}
    <button type="submit" id="upload-button" class="btn btn-danger">Cargar</button>
  </form>

</div>

{% endblock %}

{% block sidebar %}

<div class="col-md-4">
  <h3>{% trans "Permissions"  %}</h3>
  <form id="permission_form">
    {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
{% include "_permissions_form_js.html" %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val());
        }
    });
    $("#resource").select2({
        minimumInputLength: 1,
        placeholder: 'Selecciona capa, mapa o vacio',
        width: 'element',
        ajax: {
          url: '{% url 'api_dispatch_list' api_name='api' resource_name='base' %}',
          data: function(term,page){
            return {
              type: 'layer,map',
              q: term.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
            }
          },
          results: function(data) {
            return {
              results: $.map(data.results,function(object){
                return {id: object.id, text: object.title, type: object._type};
              })
            }
          }          
        }
      });
    $('#resource').on('change',function(e){$('#resource_type').val($('#resource').select2('data').type)});
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
    });
</script>
{% endblock extra_script %}

geonode/project/templates/documents/project_upload_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}project{% endblock %}

{% block body_outer %}
  <div class="col-md-12">
    <a href="{% url "project_browse" %}" class="btn btn-primary pull-right">Explora Proyectos</a>
    <h2 class="page-title"> Cargar Proyecto </h2>
  </div>
    
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}

{% endblock body_outer %}